// Public example metadata: adding an example here wires the gallery, build and capture checks.
export const examples = [
  {id:'milo',title:'A little hello.',label:'Milo / character study',alt:'Milo, an original mint-green character with a leaf antenna',features:['Curves','Rigging','Interaction'],description:'Curved shapes, a bone chain, weighted path controls and a two-state interaction. Say hello, then inspect the editable character in Studio.',inspect:'Select shoulder in Animate and scrub Hello; inspect wave arm weights in Design.'},
  {id:'orbit',title:'A loop to get lost in.',label:'Orbit / motion study',alt:'A mint-green planet with a peach-colored satellite',features:['Groups','Rotation','Easing'],description:'A small orbit assembled from nested groups and solid curved shapes. One rotation track turns the satellite into a reusable motion study.',inspect:'Select satellite in Animate and inspect the Orbit rotation track.'},
  {id:'bloom',title:'Rooted. Still moving.',label:'Bloom / deformation study',alt:'An original mint sprout with three leaves and a peach pot',features:['Bone chains','Weighted controls','Curves'],description:'A flexible stem bends through a two-bone chain. Different anchor and handle weights keep the lower stem rooted while the upper shape follows the breeze.',inspect:'Select flexible stem in Design to inspect its weights; scrub Breeze and compare root joint with tip joint.'},
  {id:'tempo',title:'Give time a little color.',label:'Tempo / timeline study',alt:'Three colored columns and markers on a rounded motion-study card',features:['Color keys','Hold keys','Cubic easing'],description:'Three columns share a rhythm but use different timing: smooth cubic motion, linear movement and stepped holds. Fill keys move between mint and peach.',inspect:'Select smooth column, linear column and stepped column in Animate; compare height, fill and key easing in Rhythm.'},
  {id:'signal',title:'A small moment of yes.',label:'Signal / interface study',alt:'An original rounded interface card with a circular status symbol',features:['Typed inputs','AND conditions','Click / trigger / reset'],description:'Enable the interface and raise the level to 50 to reach Ready. Celebrate invokes a click listener and a transient trigger. Reset restores the initial state and inputs.',inspect:'Open Interact to inspect Flow: boolean enabled, number level, trigger celebrate and the celebration pad listener.'},
];
export const exampleIds = examples.map(example=>example.id);
